export default [
  {
    url: "/panel",
    name: "Inicio",
    slug: "home",
    icon: "HomeIcon",
    permiso: 'VER MENU INICIO',
  },
  {
    url: "/panel/show-ro",
    name: "R.O",
    slug: "ro",
    icon: "BoxIcon",
    permiso: 'VER MENU RO',
  },
  {
    url: "/panel/create-group-email",
    name: "Grupo De Correos",
    slug: "grupo-de-correos",
    icon: "MailIcon",
    permiso: 'VER MENU GRUPO DE CORREOS',
  },
  {
    url: "/panel/perfiles-usuarios",
    name: "Roles",
    slug: "roles",
    icon: "UserIcon",
    permiso: 'VER MENU ROLES',
  },
  {
    url: "/panel/users",
    name: "Usuarios",
    slug: "usuarios",
    icon: "UsersIcon",
    permiso: 'VER MENU USUARIOS',
  },
  {
    url: "/panel/reports",
    name: "Reportes",
    slug: "reportes",
    icon: "CheckIcon",
    permiso: 'VER MENU REPORTES',
  },
  {
    url: "/panel/division",
    name: "Divisiones",
    slug: "divisiones",
    icon: "BookIcon",
    permiso: 'VER MENU DIVISIONES',
  },
  {
    url: "/panel/charge",
    name: "Cargos",
    slug: "cargos",
    icon: "SettingsIcon",
    permiso: 'VER MENU CARGOS',
  },
  {
    url: "/panel/job-dependencies",
    name: "Dependencias",
    slug: "dependencias",
    icon: "EditIcon",
    permiso: 'VER MENU DEPENDENCIAS',
  },
  {
    url: "/panel/resume-team",
    name: "Resumen Equipo",
    slug: "resumen-equipo",
    icon: "PowerIcon",
    permiso: '',
  },
  {
    url: "/panel/resume-area",
    name: "Resumen Area",
    slug: "resumen-area",
    icon: "LockIcon",
    permiso: 'VER MENU RESUMEN EQUIPO',
  },
  {
    url: "/panel/typing-template",
    name: "Plantillas",
    slug: "plantillas",
    icon: "SendIcon",
    permiso: 'VER MENU PLANTILLAS',
  },
]
